name: dev-print

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: dev-print
              run: echo "Printing for dev branch push"
              