name: stdlib-template

on: push

jobs:
    stdlib-template:
        name: stdlib-template
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              